# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'SimulatorConnectObjCDemo' do
  # workspace 'HotSpotTest'
  project 'SimulatorConnectObjCDemo.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LaunchMonitor
  pod 'AWSMobileClient'
end